FROM python:3.8

RUN apt-get update -y
RUN apt-get install redis-server -y 
RUN pip3 install --upgrade setuptools pip
RUN apt-get install libsm6 libxext6 libxrender1 libglib2.0-0 ffmpeg openmpi-bin libopenmpi-dev -y
RUN pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html